"""add timestamps to visits and schools

Revision ID: c7d539a3bb8a
Revises: 26ff740ab8f7
Create Date: 2026-01-15 00:03:56.087429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7d539a3bb8a'
down_revision: Union[str, Sequence[str], None] = '26ff740ab8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('schools', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('schools', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('schools', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'schools', ['email'])
    op.add_column('visits', sa.Column('status', sa.String(), nullable=False))
    op.add_column('visits', sa.Column('has_pc', sa.Boolean(), nullable=False))
    op.add_column('visits', sa.Column('has_videobeam', sa.Boolean(), nullable=False))
    op.add_column('visits', sa.Column('students_number', sa.Integer(), nullable=False))
    op.add_column('visits', sa.Column('observations', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('visits', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('visits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('visits', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('visits', 'equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('visits', 'deleted_at')
    op.drop_column('visits', 'updated_at')
    op.drop_column('visits', 'created_at')
    op.drop_column('visits', 'observations')
    op.drop_column('visits', 'students_number')
    op.drop_column('visits', 'has_videobeam')
    op.drop_column('visits', 'has_pc')
    op.drop_column('visits', 'status')
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'deleted_at')
    op.drop_column('schools', 'updated_at')
    op.drop_column('schools', 'created_at')
    op.drop_column('schools', 'email')
    # ### end Alembic commands ###
